### PR TITLE
Si5351 init does not initialize the ref freq ] nor corr ] entries for clkin #98

### PR DESCRIPTION
**Pull request by conr2286**
Ugh... I forgot about the stupid MacOS .DS_Store file which got committed in addition to si5351.cpp (please delete the silly thing).  :(

### CODE REVIEW

**Comment by NT7S** [comment]
Thanks for the PR, I'll look at getting it in there soon.

**Comment by conr2286** [comment]
I've pushed removal of .DS_Store onto the Si5351-init-does-not... branch

**Comment by conr2286** [comment]
Done.

JimC

**Review by NT7S — APPROVED** [review]
Thanks for the fix

**Pull request merged**
